# Generated by Django 6.0.1 on 2026-04-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('member', 'Member'), ('customer', 'Customer')], default='member', max_length=20),
        ),
    ]
