# Generated by Django 6.0.1 on 2026-04-14 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='member',
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
