# Generated by Django 6.0.1 on 2026-04-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_remove_loan_member_loan_borrower_delete_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_ban_book', 'Can ban book from library'), ('can_feature_book', 'Can feature book on Homepage'), ('can_bulk_import', 'Can bulk import books')]},
        ),
    ]
