# Generated by Django 6.0.1 on 2026-05-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='place_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
