# Generated by Django 6.0.1 on 2026-05-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0013_userprofile_phone_number_userprofile_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('pending_payment', 'Pending Payment'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
