# Generated by Django 5.2.8 on 2026-02-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag_alter_posts_id_posts_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
