# Generated by Django 6.0.1 on 2026-05-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_order_id_alter_orderitem_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
