# Generated by Django 6.0.1 on 2026-02-11 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
